### PR TITLE
upgrade to elm 0.18

### PR DESCRIPTION
**Pull request by mbylstra**
I used elm-upgrade which also applies elm-format, which is why there are so many lines of code changed. It was a really easy process. I did the upgrade because I want to add a small pull request -- coming soon.

### CODE REVIEW

**Comment by yupferris** [comment]
Hmm, my initial reaction is it's quite unfortunate that the upgrade changed so many files. I would have at least preferred the upgrade and formatting to be separate commits, but is it really necessary that it applies formatting? Some of this hurts readability quite badly, eg https://github.com/yupferris/elmsteroids/pull/2/commits/d6fc5b5b187628976cef4f9c6db3701af0013145#diff-ceaea231209c9596f09f43d5db6fecdaL21.

**Comment by yupferris** [comment]
It seems to me the only really necessary changes for the upgrade happened in `elm-package.json`. If possible could the PR be updated to only contain such necessary changes, without the formatting ones?

**Comment by mbylstra** [comment]
Sorry, i don't have any time to work on this.

**Comment by yupferris** [comment]
ok :)

**Pull request closed without merging**
